import type { Metadata } from "next";
import { El_Messiri } from "next/font/google";
import "./globals.css";
import I18nProvider from "./components/I18nProvider";
import LanguageSwitcher from "./components/LanguageSwitcher";
const elMessiri = El_Messiri({
  variable: "--font-el-messiri",
  display: 'swap',
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={`${elMessiri.className} antialiased`}
      >
        <I18nProvider>
          <header className="flex justify-end p-4 bg-white shadow">
            <LanguageSwitcher />
          </header>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
